export const mockProjects = [
    {
        name: "The Legacy of War Program",
        image: "legacy",
        secondaryImage: "legacy2",
        body: `The United States has been at war for over two decades. While this has hardly registered at home, it has fundamentally altered societies across the Middle East and South Asia. The Legacy of War Program seeks to carry out in-depth, granular research on the consequences of U.S. militarism, as well as to provide humanitarian support for victims of war and advocate on their behalf. The Program also studies the legacies of war of other actors, including regional governments and non-state actors like the Islamic State, and seeks to advocate on behalf of those affected by dictatorship and extremism. 

        Support for Survivors of Coalition Airstrikes – the U.S.-led air war against the Islamic State has potentially killed tens of thousands of civilians in Iraq and Syria. Until now, most of these victims and their loved ones have not received condolence payments that they are eligible for under U.S. law, nor have they received support for medical bills and lifelong disabilities. At Zomia, we are working with survivors and legal experts to redress civilian harm and to coordinate medical support.
        
        Birth Defects in Fallujah – The Iraqi city of Fallujah has suffered three major conflicts in recent years, including the U.S.-led Operation Phantom Fury in 2004. In the wake of this devastating assault, Iraqi physicians noted an increase in birth anomalies, which some experts contend is linked to the massive deployment of American weaponry. Partnering with Drexel University and Arizona State University, Zomia researchers are studying the levels and effects of lead and depleted uranium on birth outcomes. The project is part of a larger effort to identify public health consequences of war, and in particular, the legacy of lead on cognitive and physical development in post-conflict environments.
        
        Syrian Bombing Survey – Between 2014 and 2019, the U.S. carried out one of the most intensive aerial bombing campaigns in recent history, targeting Islamic State strongholds in eastern Syria and in Iraq. Cities like Raqqa and parts of Mosul lay in ruins as a result, while the conflict remains the most understudied of America’s recent wars. Zomia is conducting the first-ever bombing survey of eastern Syria—and the first attempt at a systematic bombing survey of a theater of conflict since World War II—in order to document the consequences of bombardment to infrastructure and civilian lives. By determining the location and effects of bombings, including, where possible, a complete roster of bombardment sites, we hope to illuminate the consequences of modern air war and support survivors of these attacks.
        
        Coding Bootcamp for Afghan Refugees - Last summer more than 65,000 Afghans escaped the Taliban and resettled in the US. While they’re no longer in harm’s way, the challenge of social and economic integration into America may prove to be one of their greatest challenges yet. Most new arrivals lack transferable skills and their work experience doesn’t translate to the American job market. Without training and support, these new arrivals will most likely be forced into low-income jobs with little chance of advancement. A new Zomia Center program aims to better incorporate Afghans into the US economy by creating a coding bootcamp. The initiative will provide those starting with limited to no technical skills with the knowledge and training required to find well-paid jobs in the tech sector. `,
    },
    {
        name: "Public Health Partners Program",
        image: ["health1"],
        body: `Public health is a population-centric approach to the medical needs of individuals and communities. While third-party NGOs can administer broad-based public health programs, such as vaccination and awareness campaigns, effective long-term public health planning requires democratic accountability and population-level management—which governments, not private entities, are most well-suited to deliver. Zomia assists non-state actors and community groups in taking on the responsibilities of public health delivery, especially in conflict settings or in regions where population-centric healthcare faces challenges.
 
        Vaccination Study – Since 2001, the number of civil wars across the globe has increased 30 percent, leading to a proliferation of ungoverned and semi-governed spaces — territory under the control of militias, insurgent groups, or other autonomous local actors. This poses an acute challenge to public health; one scholar noted that "75 percent of epidemics during the last three decades have occurred in countries where war, conflict, and prolonged political violence have crippled their capacity to respond, leaving their neighbors and the world vulnerable.” In particular, these areas are potential sources of pandemics and “superbugs.” But successful public health programs require strong state actors, international coordination, and systemic solutions. This ongoing study explores public health in non-state spaces, focusing attention particularly on how basic health services become privatized during times of war, and the inherent weaknesses of relying on third-party actors (such as international NGOs) to implement public health programs. The current phase of the study focuses on vaccine delivery. 
        
        Covid-19 Support – Working with local and international partners, Zomia has supported Covid-19 preparedness in non-state regions in the Middle East and South Asia; we have supported the design and development of case management protocols, produced and distributed masks, and worked with ground authorities to increase awareness of vaccination and social distancing.
         
        Leishmaniasis – Leishmaniasis is a parasitic disease that can cause disfigurement through skin lesions and, in some varieties, can prove fatal. The disease is linked with malnutrition, a weak immune system, and poor living conditions; it is an illness of poverty. Zomia works with local authorities in the Middle East to spray houses in prone areas in order to protect against the illness. Zomia also helps train local authorities and local organizations to design and implement spraying campaigns.
        `,
    },
];
